#!/bin/bash

set -e

exec 3>&1
exec 1>&2

set +x

payload=$(mktemp /tmp/bldr-resource-check.XXXXXX)

cat > "${payload}" <&0

base_uri="https://bldr.habitat.sh/v1/depot"
origin="$(jq -r '.source.origin' < "${payload}")"
name="$(jq -r '.source.name' < "${payload}")"
version="$(jq -r '.source.version // ""' < "${payload}")"
if [[ ${version} != "" ]]; then
  version="/${version}"
fi
channel="$(jq -r '.source.channel // "unstable"' < "${payload}")"

latest_version="$(jq -r '.version.pkg' < "${payload}")"

if [[ ${latest_version} == 'null' ]]; then
  curl "${base_uri}/pkgs/${origin}/${name}/latest" | \
    jq '.channels[] | select(. | contains("bldr-"))' >&3
else
  curl "${base_uri}/channels/${origin}/${channel}/pkgs/${name}${version}" 2>/dev/null | \
    jq --arg current ${latest_version} '.data[0] | .channels[] | select(. | contains("bldr-"))' >&3
fi
