#!/bin/bash

set -e

exec 3>&1
exec 1>&2

set +x

payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > "${payload}" <&0

base_uri="https://bldr.habitat.sh/v1/depot/"
group="$(jq -r '.version.group' < "${payload}")"
build_id="$(jq -r '.version.group | split("-")| .[] | select(.!= "bldr")' < "${payload}")"
filename="$(echo ${group})"

curl "${base_uri}/pkgs/schedule/${build_id}" | \
  jq '{ group: [ .projects[] | select(.name | contains("core/")) ]}' > \
  "${1}/${filename}"

jq -n --arg group "${group}" '{version: { group: $group }}' >&3
